Update libpqxx. Address software requirements

diff --git a/share_libs/libpqxx/tools/lint b/share_libs/libpqxx/tools/lint
--- a/share_libs/libpqxx/tools/lint
+++ b/share_libs/libpqxx/tools/lint
@@ -1,22 +1,72 @@
-#! /bin/sh
+#! /bin/bash
 #
 # Routine sanity checks for libpqxx source tree.
 #
-# An environment variable "srcdir" should hold the source directory.  It
-# defaults to the current directory, but it needs to be set for out-of-tree
-# builds.
+# Optionally, set environment variable "srcdir" to the source directory.  It
+# defaults to the parent directory of the one where this script is.  This trick
+# requires bash (or a close equivalent) as the shell.
 
-set -e
-set -u
+set -eu -o pipefail
+
+SRCDIR="${srcdir:-$(dirname "${BASH_SOURCE[0]}")/..}"
+PQXXVERSION="$(cd "$SRCDIR" && "$SRCDIR/tools/extract_version")"
+
+ARGS="${1:-}"
 
 
-SRCDIR="${srcdir:-.}"
-PQXXVERSION="$($SRCDIR/tools/extract_version)"
+set_up() {
+    MY_VENV="$(mktemp -d)"
+    if [ -z "$MY_VENV" ]
+    then
+        echo "Failed to set up virtualenv." >&2
+        exit 2
+    fi
+    virtualenv -q "$MY_VENV"
+    # shellcheck disable=SC1091
+    . "$MY_VENV/bin/activate"
+    pip install -q pyflakes ruff shellcheck-py
+}
+
+
+clean_up() {
+    if [ -n "${MY_VENV:-}" ] && [ "${VIRTUAL_ENV:-x}" = "${MY_VENV:-y}" ]
+    then
+        deactivate || true
+    fi
+    if [ -n "${MY_VENV:-}" ] && [ -d "${MY_VENV:-/nonexistent/dir}" ]
+    then
+        rm -r "$MY_VENV"
+    fi
+}
+
+
+trap clean_up EXIT
+set_up
+
+
+# Check that all source code is ASCII.
+#
+# I'd love to have rich Unicode, but I can live without it.  But we don't want
+# any surprises in contributions.
+check_ascii() {
+    local exotics
+    exotics="$(
+        find "$SRCDIR" -type f -name '*.[ch].cxx' -print0 |
+        xargs -0 cat |
+        tr -d '\011-\176' |
+        wc -c
+    )"
+    if [ "$exotics" != 0 ]
+    then
+        echo >&2 "There's a non-ASCII character somewhere."
+        exit 1
+    fi
+}
 
 
 # This version must be at the top of the NEWS file.
 check_news_version() {
-    if ! head -n1 $SRCDIR/NEWS | grep -q "^$PQXXVERSION\$"
+    if ! head -n1 "$SRCDIR/NEWS" | grep -q "^$PQXXVERSION\$"
     then
         cat <<EOF >&2
 Version $PQXXVERSION is not at the top of NEWS.
@@ -29,39 +79,33 @@ EOF
 # Count number of times header $1 is included from each of given input files.
 # Output is lines of <filename>:<count>, one line per file, sorted.
 count_includes() {
-    local HEADER_NAME WS PAT
+    local HEADER_NAME PAT
     HEADER_NAME="$1"
     shift
-    WS="[[:space:]]*"
-    PAT="^${WS}#${WS}include${WS}[<\"]$HEADER_NAME[>\"]"
-    grep -c "$PAT" $* | sort
+    PAT='^[[:space:]]*#[[:space:]]*include[[:space:]]*[<"]'"$HEADER_NAME"'[>"]'
+    # It's OK for the grep to fail.
+    find "$SRCDIR/include/pqxx" -type f -print0 |
+        ( xargs -0 grep -c "$PAT" || true ) |
+        sort
 }
 
 
 # Check that any includes of $1-pre.hxx are matched by $1-post.hxx ones.
 match_pre_post_headers() {
-    local NAME TEMPDIR PRE POST HEADERS
+    local NAME TEMPDIR PRE POST
     NAME="$1"
-    TEMPDIR="$(mktemp -d)"
-    if test -z "$TEMPDIR"
-    then
-        echo >&2 "Could not create temporary directory."
-        exit 1
-    fi
+    TEMPDIR="$MY_VENV/tmp-lint"
+    mkdir -p  "$TEMPDIR"
     PRE="$TEMPDIR/pre"
     POST="$TEMPDIR/post"
-    HEADERS=$(find include/pqxx/* -type f | grep -v '\.swp$')
-    count_includes \
-        $SRCDIR/NAME-pre.hxx $HEADERS >"$PRE"
-    count_includes \
-        $SRCDIR/NAME-post.hxx $HEADERS >"$POST"
-    DIFF="$(diff "$PRE" "$POST")" || /bin/true
+    count_includes "$SRCDIR/$NAME-pre.hxx" >"$PRE"
+    count_includes "$SRCDIR/$NAME-post.hxx" >"$POST"
+    DIFF="$(diff "$PRE" "$POST")" || true
     rm -r -- "$TEMPDIR"
     if test -n "$DIFF"
     then
         cat <<EOF >&2
-The number of inclusions of compiler-internal.post.hxx does not match the
-number of inclusions of compiler-internal.pre.hxx:
+Mismatched pre/post header pairs:
 
 $DIFF
 EOF
@@ -70,53 +114,114 @@ EOF
 }
 
 
-# Any file that includes compiler-internal-pre.hxx must also include
-# compiler-internal-post.hxx, and vice versa.
+# Any file that includes header-pre.hxx must also include header-post.hxx, and
+# vice versa.  Similar for ignore-deprecated-{pre|post}.hxx.
 check_compiler_internal_headers() {
-    match_pre_post_headers "pqxx/internal/compiler-internal"
+    match_pre_post_headers "pqxx/internal/header"
     match_pre_post_headers "pqxx/internal/ignore-deprecated"
 }
 
 
 cpplint() {
-    local cxxflags
+    local dialect includes
 
-    if which clang-tidy >/dev/null
+    pip install -q clang-tidy
+    if [ -e compile_flags ]
     then
-        if test -e compile_flags
-        then
-            cxxflags=$(cat compile_flags)
-        else
-            cxxflags=""
-        fi
+        # Pick out relevant flags, but leave out the rest.
+        # If we're not compiling with clang, compile_flags may contain
+        # options that clang-tidy doesn't recognise.
+        dialect="$(grep -o -- '-std=[^[:space:]]*' compile_flags || true)"
+        includes="$(
+            grep -o -- '-I[[:space:]]*[^[:space:]]*' compile_flags ||
+            true)"
+    else
+        dialect=""
+        includes=""
+    fi
 
 # TODO: Please, is there any way we can parallelise this?
-        clang-tidy \
-            $(find $SRCDIR/src $SRCDIR/tools $SRCDIR/test -name \*.cxx) \
-            --checks=abseil-*,boost-*,cppcoreguidelines-* \
-            -- \
-            -I$SRCDIR/include -Iinclude $cxxflags
+# TODO: Check test/, but tolerate some of the dubious stuff tests do.
+    # shellcheck disable=SC2086,2046
+    clang-tidy "$SRCDIR"/src/*.cxx "$SRCDIR"/tools/*.cxx \
+        -- \
+        -I"$SRCDIR/include" -Iinclude $dialect $includes
+
+    # Run Facebook's "infer" static analyser, if available.
+    # A "pip install" didn't work for me: No module named 'nltk'.
+    # Instructions here: https://fbinfer.com/docs/getting-started/
+    if which infer >/dev/null
+    then
+        # This will work in an out-of-tree build, but either way it does
+        # require a successful "configure", or a cmake with the "make"
+        # generator.
+        infer capture -- make -j"$(nproc)"
+        infer run
     fi
 }
 
 
 pylint() {
-    local PYFILES="$SRCDIR/tools/*.py $SRCDIR/tools/splitconfig"
-    echo "Skipping pocketlint; it's not up to date with Python3."
-    # if which pocketlint >/dev/null
-    # then
-    # 	pocketlint $PYFILES
-    # fi
-
-    echo "Skipping flake8; it's not up to date with Python3."
-    # if which flake8 >/dev/null
-    # then
-    # 	flake8 $PYFILES
-    # fi
+    pyflakes "$SRCDIR"/tools/*.py
+    ruff check "$SRCDIR"/tools/*.py
 }
 
 
-cpplint
-pylint
-check_news_version
-check_compiler_internal_headers
+shelllint() {
+    local TLS="deprecations extract_version format lint todo update-copyright"
+    shellcheck "$SRCDIR/autogen.sh"
+    for s in $TLS
+    do
+        shellcheck "$SRCDIR/tools/$s"
+    done
+}
+
+
+mdlint() {
+    if which mdl >/dev/null
+    then
+        find . -name \*.md -exec mdl -c .markdownlint.yaml '{}' ';'
+    fi
+}
+
+
+main() {
+    local full="no"
+    for arg in $ARGS
+    do
+        case $arg in
+        -h|--help)
+            cat <<EOF
+Perform static checks on libpqxx build tree.
+
+Usage:
+    $0 -h|--help -- print this message and exit.
+    $0 -f|--full -- perform full check, including C++ analysis.
+    $0 -- perform default check.
+EOF
+            exit 0
+        ;;
+        -f|--full)
+            full="yes"
+        ;;
+        *)
+            echo >&2 "Unknown argument: '$arg'"
+            exit 1
+        ;;
+        esac
+    done
+
+    check_ascii
+    pylint
+    shelllint
+    check_news_version
+    check_compiler_internal_headers
+    mdlint
+    if [ $full == "yes" ]
+    then
+        cpplint
+    fi
+}
+
+
+main
